org: teepha
app: petsdeli-code-challenge
service: petsdeli-code-challenge
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  userInteraction:
    handler: src/handler.create
    events:
      - httpApi:
          path: /users/interactions
          method: post
